config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :elec_solutions

  root "home#index"
  get "home/profile"
  get "home/batteries"
  get "home/solar"
  get "home/inverters"
  get "home/install"
  get "home/inquire"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/elec_solution.rb
class ElecSolution < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end


module ApplicationHelper
    include ImageHelpers
  end

app/controllers/elec_solutions_controller.rb
class ElecSolutionsController < ApplicationController
  before_action :set_elec_solution, only: %i[ show edit update destroy ]

  # GET /elec_solutions or /elec_solutions.json
  def index
    @elec_solutions = ElecSolution.all
  end

  # GET /elec_solutions/1 or /elec_solutions/1.json
  def show
  end

  # GET /elec_solutions/new
  def new
    @elec_solution = ElecSolution.new
  end

  # GET /elec_solutions/1/edit
  def edit
  end

  # POST /elec_solutions or /elec_solutions.json
  def create
    @elec_solution = ElecSolution.new(elec_solution_params)

    respond_to do |format|
      if @elec_solution.save
        format.html { redirect_to elec_solution_url(@elec_solution), notice: "Elec solution was successfully created." }
        format.json { render :show, status: :created, location: @elec_solution }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @elec_solution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /elec_solutions/1 or /elec_solutions/1.json
  def update
    respond_to do |format|
      if @elec_solution.update(elec_solution_params)
        format.html { redirect_to elec_solution_url(@elec_solution), notice: "Elec solution was successfully updated." }
        format.json { render :show, status: :ok, location: @elec_solution }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @elec_solution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elec_solutions/1 or /elec_solutions/1.json
  def destroy
    @elec_solution.destroy

    respond_to do |format|
      format.html { redirect_to elec_solutions_url, notice: "Elec solution was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_elec_solution
      @elec_solution = ElecSolution.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def elec_solution_params
      params.require(:elec_solution).permit(:first_name, :last_name, :email, :phone, :state)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def profile 
    
  end;

  def about

  end

  def batteries

  end

  def inverters

  end

  def inquire

  end

  def install

  end


  def solar

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/elec_solutions_helper.rb
module ElecSolutionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang = "en">
  <meta charset="UFT-8">
  <meta name ="viewport" content="width=device-width">
<title>ELec Solutions</title>
<body>

  <header class ="header">
    <div class logo-box>
      <% image_tag("logo.png" , class: "logo") %>
    </div>

    <div class = "text-box">
    <h1 class = "heading-primary">
      <span class = "heading-primary-main">Elec Solutions</span>
      <span class ="heading-primary-sub">Your One stop for Power Solutions</span>
    </h1>
    <a href="#" class = "btn-btn btn-white">Discover Our Solutions</a>
    </div>
  </header>
</body>
</html>

app/views/home/profile.html.erb
<body>
   
<div class = "card" style="width: 25rem;">
       <form action="upload.php" method="post" enctype="multipart/form-data">  
        <input type="file" name="Profile Picture" accept="image/*" capture="camera">  
        <input type="submit" value="Upload">  
     </form>
    <div class="card-body">
        <h2 class="card-title name">Your Profile <span class = "status"></span></h2>
        <div class = "bottom">
        <h4 class = "title ">Your Details</h4>
        <button class = "profile-action">View Preference</button>
        <button class = "profile-action">Open account Setting</button>
        <button class = "profile-action">Edit Your Project</button>
        <button class = "profile-action">View Your Files</button>
        <button class = "profile-action">Set yourself away</button>
        </div>


    </div>
</div>
</body>

app/views/layouts/_header.html.erb
<nav class=" navbar navbar-expand-lg sticky-top navbar-light bg-light">
          
    <div class="container-fluid">
      <a class="navbar-brand text-center" href=<%=root_path%> ><%=image_tag('logo.png', alt: "logo", class: "logo") %></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse nav-bar-destop navbar-collapse" id="navbarTogglerDemo01">
        <ul class="navbar-nav mx-auto me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "Battery", home_batteries_path, class: "nav-link nav-link-color", class: "btn auth-btn small-btn login-btn" %>

          </li>
          <li class="nav-item">
            <%= link_to "Inverters", home_inverters_path, class: "nav-link nav-link-color", class: "btn auth-btn small-btn login-btn" %>
          </li>
          <li class="nav-item">
            <%= link_to "Solar", home_solar_path, class: "nav-link nav-link-color", class: "btn auth-btn small-btn login-btn" %>
          </li>
          <li class="nav-item">
            <%= link_to "Installation", home_install_path, class: "nav-link nav-link-color", class: "btn auth-btn small-btn login-btn" %>
          </li>

          <li class="nav-item">
            <%= link_to "FAQs", home_inquire_path, class: "nav-link nav-link-color", class: "btn auth-btn small-btn login-btn" %>
          </li>

        </ul>
        <div class="d-flex">
             <%= link_to "Sign Out", destroy_user_session_path , method: :delete , class: "btn auth-btn small-btn register-btn" %>
            <%=link_to "Log in", new_user_session_path , class: "btn auth-btn small-btn login-btn" %>
            <%= link_to "Register", new_user_registration_path , class: "btn auth-btn register-btn small-btn" %>
            <%= link_to "Profile", home_profile_path , method: :delete , class: "btn auth-btn small-btn login-btn" %>
        </div>
      </div>
  
      <div class=" nav-item mobile-path">
        <div class = "search-container">
        </div>
          <a href= <% destroy_user_session_path %> class="mobile-login-btn">
            <h3 class = "signout">Signout</h3>
          </a>

          <a href= <% new_user_session_path%> class="mobile-login-btn">
            <h3 class="mobile-icon">Login</h3>
          </a>
          <a href= <%= new_user_registration_path %> class="mobile-register-btn">
            <h3 class="mobile-icon">Register</h3>
          </a>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
     <title>Elecsolution</title>
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>

 <%=  render "layouts/header" %>
 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>
<%= yield %>


  </body>
</html>